# Copyright (c) 2021 Cannlytics <contact@cannlytics.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Cannlytics
site_url: https://docs.cannlytics.com/
site_author: Keegan Skeate
site_description: >-
  Cannlytics is simple, easy-to-use, end-to-end cannabis analytics software
  designed to make data and information accessible. We believe that everyone in the
  cannabis industry should be able to access rich, valuable data quickly and easily and
  that everyone, especially yourself, will be better off for it.

# Repository
repo_name: Cannlytics
repo_url: https://github.com/cannlytics/cannlytics
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Cannlytics

# Configuration
docs_dir: docs/src
site_dir: docs/build

# Theme
theme:
  name: material
  custom_dir: docs/theme
  favicon: assets/images/favicon.ico
  logo: assets/images/cannlytics_calyx_512.svg
  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Lora
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tracking
    # Optional: Explore additional features.
    # - navigation.sections
    # - navigation.instant
  # Optional: Custom 404 page.
  # static_templates:
  #   - partials/404.html
  

# Site map
nav:
  - Home: index.md

  # About
  #------------
  - About:
    - Overview: about/about.md
    - Frequently Asked Questions: about/faq.md
    - Support: about/support.md
    - Change Log: changelog.md
    - License: about/legal/licenses/license.md
    # - Privacy policy: about/legal/privacy-policy.md
    # - Security policy: about/legal/security-policy.md
    # - Terms of service: about/legal/terms-of-service.md

  # API
  #------------
  - API:
    - Introduction: api/about.md
    - Getting Started: api/get-started.md
    - Authentication: api/auth/authentication.md
    - Endpoints:
      - Analyses: api/endpoints/analyses.md
      - Areas: api/endpoints/areas.md
      - Contacts: api/endpoints/contacts.md
      - Instruments: api/endpoints/instruments.md
      - Inventory: api/endpoints/inventory.md
      - Invoices: api/endpoints/invoices.md
      - Organizations: api/endpoints/organizations.md
      - Projects: api/endpoints/projects.md
      - Results: api/endpoints/results.md
      - Samples: api/endpoints/samples.md
      - Settings: api/endpoints/settings.md
      - Traceability: api/endpoints/traceability.md
      - Transfers: api/endpoints/transfers.md
      - Users: api/endpoints/users.md
  
  # Users
  #------------
  - Users:
    - Getting Started: console/get-started.md
    - Authentication:
      - Introduction: console/auth/authentication.md
      - Sign Up: console/auth/sign_up.md
    - Analyses: console/lims/analyses/analyses.md
    - Analytes: console/lims/analytes/analytes.md
    - Areas: console/lims/areas/areas.md
    - Data Review:
      - Data: console/lims/data/data.md
      - Data Review: console/lims/review/data_review.md
      - Data Analysis: console/lims/data/data_analysis.md
      - Importing and exporting data: console/lims/data/exports.md
      - Generating CoAs: console/lims/review/generating_coas.md
      - Posting Results: console/lims/review/posting_results.md
      - Quality Control: console/lims/review/qc.md
      - Logs: console/lims/data/logs.md
    - Contacts: console/lims/contacts/contacts.md
    - Data Collection: console/lims/data/data_collection.md
    - Data Review: console/lims/data/data_review.md
    - Instruments: console/lims/instruments/instruments.md
    - Inventory: console/lims/inventory/inventory.md
    - Invoices: console/lims/invoices/invoices.md
    - Organizations: console/lims/organizations/organizations.md
    # - Regulations: console/regulations.md
    - Projects: console/lims/projects/projects.md
    - Results: console/lims/results/results.md
    - Samples: console/lims/samples/samples.md
    - Transfers: console/lims/transfers/transfers.md
    - Traceability: console/lims/traceability/traceability.md
    - Settings: console/lims/settings/settings.md
  
  # Developers
  #------------
  - Developers:
    - Getting Started: developers/development.md
    - Installation: developers/installation.md
    # - Development: developers/development.md
    - Contributing: developers/contributing.md
    - Packaging: developers/packaging.md
    - Publishing: developers/publishing.md
    - Roadmap: developers/roadmap.md
    - Security: developers/security.md
    - Testing: developers/testing.md
    - Version control: developers/version_control.md
    - Bugs: developers/bugs.md
    - Modules:
      - Firebase:
        - Introduction: cannlytics/firebase/firebase.md
        - API reference: cannlytics/firebase/firebase-reference.md
        # - Cloud Functions: cannlytics/firebase/cloud_functions.md
        # - Firestore: cannlytics/firebase/firestore_schema.md
      # - Leaf Data Systems Module: cannlytics/traceability/leaf.md
      - LIMS:
        - Introduction: cannlytics/lims/lims.md
        - API reference: cannlytics/lims/lims-reference.md
      - Metrc:
        - Introduction: cannlytics/traceability/metrc.md
        - API reference: cannlytics/traceability/metrc-reference.md
      # - Website: # (Add later)
      #   - Art: website/art.md
      #   - Data:
      #     - Architecture: data/data_architecture.md
      #     - Data Collection: data/data_collection.md
      #     - Data Sources: data/data_sources.md
      #     - Schemas: data/data_schemas.md
      #   - Donations: website/donations.md
      #   - Events: website/events.md
      #   - Examples: website/examples.md
      #   - Firebase: website/firebase.md
      #   - Fun: website/fun.md
      #   - Sitemap: website/sitemap.md      
      
# Extensions
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        # - name: md-render
        #   class: md-render
        #   format: !!python/name:docs.tools.pymdownx_md_render.md_sub_render
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: cannlytics
      repo: cannlytics
      # normalize_issue_symbols: true
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  # - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  # - pymdownx.snippets:
  #     base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:

# Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cannlytics
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/cannlytics/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/cannlytics

# Plugins
# Optional: Add updated at date for docs
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#revision-date-localized
plugins:
  # - admonition
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.path.append('../../')
            - sys.modules["pandas"] = mock()
            - sys.modules["firebase_admin"] = mock()
            - sys.modules["googlemaps"] = mock()
            - sys.modules["google-cloud"] = mock()
            - sys.modules["google-cloud-firestore"] = mock()
          # selection:
          #   new_path_syntax: true
  - minify:
      minify_html: true

# Optional: Setup Google Analytics
# google_analytics:
#   - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#   - auto

# Optional: Specify a development server
# dev_addr: '0.0.0.0:4200'
